### ISSUE TITLE
Type error in -s getmag stage with 2m data.

### ISSUE THREAD

**Issue by nicomeza** [LCOGT/lcogtsnpipe#103]
After successfully running zcat and mag stages, getmag stage gives a Type error and gives no output.

`
lscloop.py -n SN2021gmj -e 20210708   --filetype 3 -s getmag --type mag

Traceback (most recent cal last):
  File "/dark/anaconda/anaconda27/envs/halenv/bin/lscloop.py", line 187, in <module>
    lsc.myloopdef.run_getmag(ll['filename'], args.output, args.interactive, args.show, args.combine, args.type, args.uploadtosnex2)
  File "/dark/anaconda/anaconda27/envs/halenv/lib/python2.7/site-packages/lsc/myloopdef.py", line 110, in run_getmag
    ww = np.array([j for j in range(len(mjd0)) if (mjd0[j] - mjd0[i]) < _bin and (
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
`

**Comment by griffin-h** [comment]
This seems to be because the MJD column was not populated for these images in the database. I'm not sure how this happened. I reingested the images using `LCOGTingest.py` and it fixed the problem.
