### ISSUE TITLE
Converting `--field` to catalog name is dependent on `--name`

### ISSUE THREAD

**Issue by navii98** [LCOGT/lcogtsnpipe#105]
In `lscloop.py`, `lsc.util.getcatalog(args.name, args.field)` is called when converting `args.field` to a catalog name.
However, I've noticed that it may or may not work depending on the input of `args.name`.

e.g. if I run the psf stage (after an ad-hoc solution to #104)
`lscloop.py -n 2021foa -e xxxxxxxx -s psf --field apass`
this would not work and use the default gaia catalog,
but 
`lscloop.py -n SN2021foa -e xxxxxxxx -s psf --field apass`
would work and use the apass catalog.

**Comment by griffin-h** [comment]
I think this should be resolved by the name matching changes in #97 and #98. I'm able to find the APASS catalog regardless of how I format the name:
```
In [1]: import lsc

In [2]: lsc.util.getcatalog('2021foa', 'apass')
Out[2]: '/supernova/standard/cat/apass/ASASSN-21dg_apass.cat'

In [3]: lsc.util.getcatalog('SN2021foa', 'apass')
Out[3]: '/supernova/standard/cat/apass/ASASSN-21dg_apass.cat'

In [4]: lsc.util.getcatalog('SN 2021foa', 'apass')
Out[4]: '/supernova/standard/cat/apass/ASASSN-21dg_apass.cat'
```
Closing.
