### ISSUE TITLE
specifying a single filter in mag stage doesn't work

### ISSUE THREAD

**Issue by abostroem** [LCOGT/lcogtsnpipe#23]
When I specify ```-f U -s mag --type=fit -F``` all of the magnitudes are updated with 9999. However, if I specify ```-f landolt ``` they are all successfully calibrated.

**Comment by griffin-h** [comment]
I think this is intentional. In order to use the color terms (U-B) in the header of the U-band files, you need to include the B-band images in the `-s mag` call.

If there are only U-band images, it should work without a color term.

**Comment by abostroem** [comment]
I updated the manual to warn against this option and explain it. I'm going to close this issue
