### ISSUE TITLE
Feature request: add command-line option to use strict matching of telescopes for local sequence calibration

### ISSUE THREAD

**Issue by griffin-h** [LCOGT/lcogtsnpipe#92]
Nico Meza and I discovered that the zero points of 1m0-06 and 1m0-08 (both at ELP) are different by ~1 mag on the same nights. This may be because 1m0-06 is quite a bit newer. This causes a lot of scatter in the local sequence calibration if the supernova and the standard field were taken on different telescopes. We should add an option in the pipeline to do strict matching based on individual telescopes, rather than the current matching by site. We may even want this to be the default, while still allowing the old way for cases when there are too few standard fields observed.

**Comment by svalenti** [comment]
Wow i guess one mag lost due to degradation of mirrors
